# Generated by Django 6.0.2 on 2026-04-09 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0008_rename_court_token_verbose"),
        ("cases", "0009_rename_log_chat_verbose"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CasePreservationQuoteBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("preserve_amount_snapshot", models.DecimalField(decimal_places=2, help_text="用于复用询价时匹配案件当前金额", max_digits=15, verbose_name="绑定时保全金额")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="preservation_quote_bindings", to="cases.case", verbose_name="案件")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_case_preservation_quote_bindings", to=settings.AUTH_USER_MODEL, verbose_name="创建人")),
                ("preservation_quote", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="case_bindings", to="automation.preservationquote", verbose_name="财产保全询价")),
            ],
            options={
                "verbose_name": "案件询价绑定",
                "verbose_name_plural": "案件询价绑定",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["case", "-created_at"], name="automation__case_id_6f343e_idx"), models.Index(fields=["preservation_quote"], name="automation__preserv_69b108_idx"), models.Index(fields=["preserve_amount_snapshot"], name="automation__preserv_2b8c06_idx")],
                "constraints": [models.UniqueConstraint(fields=("case", "preservation_quote"), name="uniq_case_quote_binding")],
            },
        ),
    ]
